version: '3.9'
services:  
  inventoryservice_ps:
    build:
      context: ./inventoryservice_ps
    container_name: inventoryservice_ps_ct
    environment:
      - project_id=ada2020-305519
    ports:
      - "5000:5000"