version: '3.9'
services:
  pgdb_server:
    image: postgres:13.2
    restart: always
    container_name: pgdb_server_ct
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpass
    ports:
      - "5432:5432"
    volumes:
      - /home/indika_kuma/pgdata:/var/lib/postgresql/data
  db_admin:
    image: adminer
    restart: always
    container_name: db_admin_ct
    ports:
      - "8080:8080"
  delivery_service:
    build:
      context: ./../componets/deliveryservice
    container_name: delivery_service_ct
    environment:
      - DB_URL=postgresql://testuser:testpass@pgdb_server:5432/delivery
    depends_on:
      - pgdb_server
    ports:
      - "5000:5000"
  place_service:
    build:
      context: ./../componets/placeservice
    container_name: place_service_ct
    environment:
      - DB_URL=postgresql://testuser:testpass@pgdb_server:5432/place
    depends_on:
      - pgdb_server
    ports:
      - "5001:5000"